export type Article = {
  id: string
  paragraph: string
  title: string
  text: string
  chapter: string
  stars: number
  order: number
}

export const CHAPTERS = [
  'Preambuła',
  'Rozdział I — Zasady Ustrojowe: Naród jako Suweren',
  'Rozdział II — Prawa i Wolności Obywatelskie',
  'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu',
  'Rozdział IV — Kontrola Władzy przez Naród',
  'Rozdział V — Praworządność',
  'Rozdział VI — Zmiana Konstytucji',
  'Rozdział VII — Postanowienia Końcowe',
]

export const ARTICLES: Article[] = [
  {
    id: 'p0', paragraph: 'Preambuła', title: 'Preambuła',
    text: 'My, Naród Polski — świadomi, że władza w Rzeczypospolitej pochodzi wyłącznie od Narodu i służy wyłącznie Narodowi; przekonani, że państwo jest dobrowolnym narzędziem stworzonym przez ludzi dla ludzi — nie instytucją nadrzędną wobec swoich twórców; pamiętając ofiary i walkę wszystkich pokoleń, które broniły wolności, godności i prawa do stanowienia o sobie; zakorzenieni w ponad tysiącletniej tradycji chrześcijańskiej i katolickiej, która ukształtowała tożsamość, kulturę i etykę Narodu Polskiego — tradycji otwartej, szanującej godność każdego człowieka niezależnie od jego wyznania; dążąc do trwałego zabezpieczenia godności każdego człowieka, równości szans, wolności jednostki i dobrostanu przyszłych pokoleń; pragnąc państwa, które chroni wolność, nie ogranicza jej; które służy obywatelom, nie panuje nad nimi; które nagradza pracowitość i przedsiębiorczość, nie karze sukcesu — zawieramy niniejszy Kontrakt Społeczny, ustanawiając Konstytucję Rzeczypospolitej Polskiej jako najwyższe prawo Narodu i wiążące zobowiązanie wszystkich władz publicznych wobec obywateli.\n\nŻadna władza — ustawodawcza, wykonawcza ani sądownicza — nie jest źródłem praw człowieka. Prawa te są przyrodzone i niezbywalne. Konstytucja jedynie je potwierdza i chroni.',
    chapter: 'Preambuła', stars: 5, order: 0,
  },
  {
    id: '1', paragraph: '§ 1', title: 'Suwerenność Narodu',
    text: 'Art. 1. Rzeczpospolita Polska jest dobrem wspólnym wszystkich obywateli. Naród Polski jest jedynym i niepodzielnym suwerenem — źródłem wszelkiej władzy publicznej.\n\nArt. 2. Władza w Rzeczypospolitej pochodzi od Narodu i jest sprawowana wyłącznie w jego imieniu oraz na jego rzecz. Jakiekolwiek sprawowanie władzy bez mandatu Narodu lub wbrew jego interesom jest nielegalne.\n\nArt. 3. Naród sprawuje władzę bezpośrednio — przez referenda, inicjatywę ustawodawczą i weto obywatelskie — oraz pośrednio, przez demokratycznie wybranych przedstawicieli posiadających odrębny mandat społeczny.\n\nArt. 4. Żadna partia polityczna, organizacja, instytucja ani jednostka nie może rościć sobie prawa do sprawowania władzy suwerennej. Suwerenność Narodu jest niezbywalna i nie podlega delegacji.',
    chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5, order: 1,
  },
  {
    id: '2', paragraph: '§ 2', title: 'Charakter Państwa — Narzędzie Narodu',
    text: 'Art. 1. Państwo polskie jest instytucją służebną — powołaną do życia przez Naród w celu zabezpieczenia praw, wolności i dobrostanu obywateli. Istnieje dla ludzi, nie ludzie dla państwa.\n\nArt. 2. Organy państwowe nie posiadają władzy własnej. Wszelka władza jest im powierzona przez Naród na warunkach określonych w niniejszej Konstytucji i może być w każdym czasie odwołana lub ograniczona zgodnie z trybem tu wskazanym.\n\nArt. 3. Rząd prawa, nie ludzi — wszystkie organy państwa, bez wyjątku, działają wyłącznie na podstawie i w granicach prawa. Żaden organ, żaden urzędnik, żaden piastun władzy nie stoi ponad prawem.\n\nArt. 4. W razie sprzeczności pomiędzy interesem instytucji państwowej a dobrem Narodu, pierwszeństwo ma zawsze dobro Narodu.',
    chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5, order: 2,
  },
  {
    id: '3', paragraph: '§ 3', title: 'Godność Człowieka — Fundament Nienaruszalny',
    text: 'Art. 1. Przyrodzona i niezbywalna godność człowieka jest nienaruszalna. Jej poszanowanie i ochrona jest obowiązkiem każdego organu władzy publicznej.\n\nArt. 2. Prawa i wolności człowieka nie są nadawane przez państwo — są mu przyrodzone. Konstytucja je potwierdza i chroni. Państwo nie może ich odebrać ani zawiesić, chyba że w ściśle określonych przypadkach i wyłącznie na podstawie wyraźnego przepisu Konstytucji.\n\nArt. 3. Zakaz tortur i nieludzkiego traktowania — nikt nie może być poddany torturom, okrutnemu, nieludzkiemu lub poniżającemu traktowaniu albo karaniu. Zakaz ten nie podlega żadnym wyjątkom i nie może być uchylony żadną ustawą ani decyzją organu władzy.',
    chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5, order: 3,
  },
  {
    id: '4', paragraph: '§ 4', title: 'Tradycja Chrześcijańska jako Fundament Etyczny',
    text: 'Art. 1. Rzeczpospolita Polska czerpie z ponad tysiącletniej tradycji chrześcijańskiej i katolickiej Narodu Polskiego, która stanowi fundament etyczny systemu wartości państwa.\n\nArt. 2. Etyka chrześcijańska — oparta na godności człowieka, odpowiedzialności, solidarności i sprawiedliwości — wyznacza aksjologiczny fundament stanowienia i stosowania prawa.\n\nArt. 3. Rzeczpospolita szanuje wolność sumienia i wyznania wszystkich obywateli. Osoby innych wyznań oraz niewierzące mogą w pełni uczestniczyć w życiu publicznym i pełnić wszelkie funkcje państwowe, pod warunkiem poszanowania etycznych zasad, na których opiera się porządek konstytucyjny.\n\nArt. 4. Kościoły i związki wyznaniowe są niezależne od państwa, a państwo jest niezależne od Kościołów. Wzajemne relacje opierają się na zasadzie poszanowania autonomii i współdziałania dla dobra człowieka i Narodu.',
    chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5, order: 4,
  },
  {
    id: '5', paragraph: '§ 5', title: 'Rodzina jako Podstawowa Komórka Społeczna',
    text: 'Art. 1. Rodzina — trwały związek kobiety i mężczyzny — jest podstawową i naturalną komórką społeczną oraz gwarantem ciągłości Narodu. Rodzina jest pod szczególną ochroną prawa i państwa.\n\nArt. 2. Macierzyństwo i ojcostwo są chronione przez państwo. Rodziny wielodzietne korzystają ze szczególnego wsparcia, którego formy określa ustawa.\n\nArt. 3. Państwo wspiera rodzinę, lecz jej nie zastępuje. Rodzice mają pierwszeństwo przed państwem w wychowaniu dzieci zgodnie z własnymi wartościami i przekonaniami, w granicach prawa.',
    chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5, order: 5,
  },
  {
    id: '6', paragraph: '§ 6', title: 'Zasada Pomocniczości i Decentralizacji',
    text: 'Art. 1. Władza publiczna powinna być sprawowana na szczeblu możliwie najbliższym obywatelowi. Zadania, które mogą być realizowane na poziomie lokalnym lub regionalnym, nie są przekazywane organom centralnym.\n\nArt. 2. Wspólnoty samorządowe — gminne, powiatowe i wojewódzkie — mają zagwarantowaną sferę autonomii chronioną przed ingerencją władzy centralnej.\n\nArt. 3. Naród, rodzina i wspólnota lokalna są naturalnymi i pierwotnymi podmiotami życia społecznego. Państwo wspiera ich działanie, a nie zastępuje.',
    chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5, order: 6,
  },
  {
    id: '7', paragraph: '§ 7', title: 'Rzeczpospolita jako Państwo Prawa',
    text: 'Art. 1. Rzeczpospolita Polska jest demokratycznym państwem prawnym. Konstytucja jest najwyższym prawem Rzeczypospolitej. Wszystkie ustawy, rozporządzenia, umowy międzynarodowe i działania organów władzy muszą być z nią zgodne i precyzyjnie określone — przepisy niejasne, wieloznaczne lub pozostawiające organom władzy dowolność interpretacji są niezgodne z Konstytucją.\n\nArt. 2. Rzeczpospolita jest państwem jednolitym i niepodzielnym. Jej integralność terytorialna podlega bezwzględnej ochronie.',
    chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5, order: 7,
  },
  {
    id: '8', paragraph: '§ 8', title: 'Prawo do Życia, Wolności i Bezpieczeństwa',
    text: 'Art. 1. Każdy człowiek ma przyrodzone prawo do życia. Nikt nie może być go pozbawiony arbitralnie.\n\nArt. 2. Każdy ma prawo do wolności i bezpieczeństwa osobistego. Nikt nie może być zatrzymany, aresztowany ani pozbawiony wolności inaczej niż na zasadach i w trybie ściśle określonych ustawą. Każde zatrzymanie podlega kontroli sądowej w ciągu 48 godzin. Areszt tymczasowy nie może przekroczyć 3 miesięcy bez przedłużenia przez sąd i nie może trwać łącznie dłużej niż 12 miesięcy.\n\nArt. 3. Zakazane są wszelkie formy tortur, okrutnego traktowania, kar cielesnych oraz poniżającego traktowania lub karania — bez żadnych wyjątków i w żadnych okolicznościach.\n\nArt. 4. Każdy pozbawiony wolności ma prawo do niezwłocznej — nie później niż w ciągu 3 godzin od zatrzymania — informacji o przyczynach zatrzymania, dostępu do obrońcy i powiadomienia osoby bliskiej.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 8,
  },
  {
    id: '9', paragraph: '§ 9', title: 'Prawo do Posiadania Broni',
    text: 'Art. 1. Prawo obywatela do posiadania broni jest gwarantowane i nie może być naruszone. Prawo to służy obronie własnej, obronie rodziny oraz obronie wolności Narodu przed bezprawnym przejęciem władzy niezgodnym z niniejszą Konstytucją.\n\nArt. 2. Uzbrojony obywatel jest ostatecznym gwarantem wolności Narodu. Gdy państwo przestaje być narzędziem Narodu i staje się jego ciemiężcą, prawo do broni stanowi ostatnią linię obrony suwerenności.\n\nArt. 3. Warunki nabywania, rejestracji i szkolenia w zakresie posiadania broni określa ustawa. Ustawa nie może jednak faktycznie uniemożliwić obywatelowi realizacji tego prawa.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 9,
  },
  {
    id: '10', paragraph: '§ 10', title: 'Wolność Słowa, Prasy i Mediów',
    text: 'Art. 1. Wolność wyrażania poglądów oraz pozyskiwania i rozpowszechniania informacji jest gwarantowana. Cenzura prewencyjna jest bezwzględnie zakazana.\n\nArt. 2. Wolność prasy i innych środków masowego przekazu jest podstawą demokratycznej kontroli władzy. Pluralizm mediów jest chroniony przez prawo.\n\nArt. 3. Platformy cyfrowe, portale społecznościowe i inne media internetowe działające na terytorium Rzeczypospolitej są zobowiązane do stosowania polskich standardów wolności słowa. Nie mogą ograniczać, usuwać ani obniżać widoczności treści zgodnych z polskim prawem na podstawie własnych regulaminów, algorytmów lub decyzji podmiotów zagranicznych. Naruszenie tego zakazu jest ścigane przez niezależny organ regulacyjny.\n\nArt. 4. Zagraniczny kapitał w mediach działających na terytorium Rzeczypospolitej podlega obowiązkowi koncesjonowania. Ustawa określa dopuszczalne progi udziału kapitału zagranicznego w podmiotach medialnych, chroniąc pluralizm i niezależność polskiej przestrzeni informacyjnej.\n\nArt. 5. Wolność słowa chroni także treści niepopularne, kontrowersyjne i krytyczne wobec władzy. Jedyne dopuszczalne ograniczenia to: bezpośrednie nawoływanie do przemocy wobec konkretnych osób, nawoływanie do ludobójstwa oraz świadome rozpowszechnianie fałszywych informacji w celu szkody konkretnej osobie. Każde ograniczenie wymaga wyroku sądu.\n\nArt. 6. Każdy ma prawo do pokojowego zgromadzania się oraz do zrzeszania się.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 10,
  },
  {
    id: '11', paragraph: '§ 11', title: 'Prawo do Prywatności i Ochrony Danych',
    text: 'Art. 1. Każdy ma prawo do poszanowania prywatności życia osobistego, rodzinnego i komunikacji. Wkroczenie w sferę prywatności przez organy państwa jest dopuszczalne wyłącznie na podstawie imiennego nakazu sądu, wydanego w oparciu o konkretne, udokumentowane podejrzenie popełnienia przestępstwa dotyczące wskazanej z imienia i nazwiska osoby.\n\nArt. 2. Masowa inwigilacja obywateli — zbieranie, przetwarzanie lub analiza danych dotyczących nieoznaczonych z góry osób — jest bezwzględnie zakazana. Zakaz ten nie może być uchylony żadną ustawą ani decyzją organu władzy.\n\nArt. 3. Tajemnica korespondencji i komunikacji jest chroniona. Jej naruszenie bez imiennego nakazu sądowego stanowi przestępstwo urzędnicze ścigane z urzędu.\n\nArt. 4. Dane osobowe obywateli są chronione. Każdy ma prawo wiedzieć, jakie dane na jego temat przetwarza państwo, żądać ich sprostowania i usunięcia.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 11,
  },
  {
    id: '12', paragraph: '§ 12', title: 'Równość wobec Prawa',
    text: 'Art. 1. Wszyscy są równi wobec prawa. Konstytucja nie tworzy żadnych kategorii, grup ani klas obywateli objętych szczególną ochroną lub szczególnymi ograniczeniami. Prawo stosuje się jednolicie do wszystkich.\n\nArt. 2. Nikt nie może być dyskryminowany przez organy władzy publicznej ze względu na płeć, wiek, rasę, narodowość, pochodzenie, religię lub jej brak, przekonania polityczne, orientację seksualną, niepełnosprawność ani status majątkowy.\n\nArt. 3. Równość wobec prawa oznacza równość wszystkich — bez wyróżnionych grup, bez podziałów, bez hierarchii obywateli. Państwo nie tworzy podziałów tam, gdzie ich nie ma.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 12,
  },
  {
    id: '13', paragraph: '§ 13', title: 'Prawo do Rzetelnego Procesu',
    text: 'Art. 1. Każdy ma prawo do sprawiedliwego i publicznego rozpatrzenia sprawy przez niezawisły i bezstronny sąd. Pierwsze posiedzenie sądu w sprawie karnej odbywa się nie później niż w ciągu 30 dni od wniesienia aktu oskarżenia. Wyrok w pierwszej instancji zapada nie później niż w ciągu 12 miesięcy od pierwszego posiedzenia. Przekroczenie tych terminów bez uzasadnionych przyczyn daje stronie prawo do odszkodowania od Skarbu Państwa.\n\nArt. 2. Każdy oskarżony jest niewinny dopóki wina nie zostanie udowodniona prawomocnym wyrokiem sądu. Ciężar dowodu spoczywa wyłącznie na oskarżeniu.\n\nArt. 3. Każdy ma prawo do obrońcy od pierwszej chwili zatrzymania. Osobom nieposiadającym środków finansowych zapewnia się obrońcę z urzędu na koszt państwa.\n\nArt. 4. Zakaz samooskarżania — nikt nie ma obowiązku zeznawać przeciwko sobie. Przyznanie się do winy uzyskane pod jakimkolwiek przymusem jest nieważne z mocy prawa i stanowi przestępstwo osoby, która je wymusiła.\n\nArt. 5. Zakaz podwójnego karania — nikt nie może być sądzony ani karany za ten sam czyn więcej niż jeden raz.\n\nArt. 6. Prawo karne nie działa wstecz. Nie można wymierzyć kary surowszej niż ta, która obowiązywała w chwili popełnienia czynu.\n\nArt. 7. Rozprawa sądowa jest jawna. Wyłączenie jawności wymaga uzasadnionego postanowienia sądu i jest dopuszczalne wyłącznie dla ochrony prywatności stron lub bezpieczeństwa państwa.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 13,
  },
  {
    id: '14', paragraph: '§ 14', title: 'Równość Szans i Wolność Gospodarcza',
    text: 'Art. 1. Każdy ma prawo do swobodnego wyboru zawodu i miejsca pracy oraz do prowadzenia działalności gospodarczej. Wolność gospodarcza jest gwarantowana i może być ograniczona wyłącznie ustawą, gdy jest to niezbędne dla ochrony ważnego interesu publicznego.\n\nArt. 2. Państwo zapewnia równość szans — każdy obywatel ma prawo do dostępu do edukacji i ochrony zdrowia niezależnie od swojego statusu majątkowego. Dostęp ten nie może być wyłączony z powodu ubóstwa.\n\nArt. 3. System podatkowy nie może karać przedsiębiorczości, pracy i sukcesu. Podatki są ustanawiane wyłącznie ustawą, muszą być proporcjonalne i przewidywalne.\n\nArt. 4. Sieć bezpieczeństwa socjalnego — pomoc dla osób które znalazły się w trudnej sytuacji życiowej nie z własnej winy — jest obowiązkiem państwa. Jej zakres i formy określa ustawa. Pomoc ta jest adresowana do tych, którzy nie mogą, nie do tych, którzy nie chcą.\n\nArt. 5. Pracownicy mają prawo do zrzeszania się i prowadzenia zbiorowych negocjacji. Praca przymusowa jest zakazana.\n\nArt. 6. Każdy ma prawo do ochrony zdrowia. Państwo organizuje i finansuje ze środków publicznych podstawową opiekę zdrowotną dostępną dla każdego obywatela. Formy i zakres tej opieki określa ustawa.\n\nArt. 7. Organy i agendy państwowe nie mogą prowadzić działalności gospodarczej konkurującej z obywatelami i podmiotami prywatnymi. Wyjątkiem jest infrastruktura o charakterze naturalnego monopolu, której formy własności i zarządzania określa ustawa.\n\nArt. 8. W czasie stanu wojennego Prezydent może przejąć zarządzanie — nie własność — dowolnego podmiotu gospodarczego działającego na terytorium Rzeczypospolitej, za uprzednią zgodą Sejmu wyrażoną w ciągu 48 godzin. Przejęcie zarządzania kończy się automatycznie z chwilą ustania stanu wojennego. Właściciel zachowuje prawo własności przez cały czas. Odszkodowanie należy się wyłącznie w przypadku udowodnionej straty wartości lub utraty własności wskutek decyzji państwa.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 14,
  },
  {
    id: '15', paragraph: '§ 15', title: 'Prawo do Środowiska Naturalnego',
    text: 'Art. 1. Każdy ma prawo do życia w zdrowym środowisku naturalnym. Ochrona środowiska jest obowiązkiem organów władzy publicznej i każdego podmiotu gospodarczego działającego na terytorium Rzeczypospolitej.\n\nArt. 2. Zasoby naturalne Rzeczypospolitej — ziemia, wody, lasy i kopaliny — są dobrem Narodu. Ich eksploatacja musi służyć dobru wspólnemu i nie może narażać przyszłych pokoleń na trwałe szkody środowiskowe.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 15,
  },
  {
    id: '16', paragraph: '§ 16', title: 'Ograniczenia Praw i Wolności',
    text: 'Art. 1. Prawa i wolności zawarte w niniejszym rozdziale mogą być ograniczone wyłącznie w drodze ustawy, która musi precyzyjnie określać zakres ograniczenia, jego cel oraz czas trwania. Przepisy ograniczające prawa nie mogą być niejasne ani wieloznaczne.\n\nArt. 2. Każde ograniczenie musi być proporcjonalne do chronionego celu i stanowić środek najmniej uciążliwy dla obywatela spośród skutecznych. Sąd Konstytucyjny kontroluje proporcjonalność wszystkich ograniczeń.\n\nArt. 3. Istota żadnego prawa i wolności nie może być naruszona. Zakaz tortur z § 8 art. 3 i domniemanie niewinności z § 13 art. 2 nie podlegają żadnym ograniczeniom w żadnych okolicznościach.',
    chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5, order: 16,
  },
  {
    id: '17', paragraph: '§ 17', title: 'Zasada Trójpodziału, Odrębnych Mandatów i Wzajemnej Kontroli',
    text: 'Art. 1. Władza ustawodawcza, wykonawcza i sądownicza są od siebie oddzielone, wzajemnie się równoważą i każda z nich posiada odrębny mandat społeczny udzielony bezpośrednio przez Naród. Koncentracja więcej niż jednej spośród tych władz w jednym organie lub jednej osobie jest zakazana i nieważna z mocy prawa.\n\nArt. 2. Każda z władz działa wyłącznie w granicach kompetencji przyznanych jej niniejszą Konstytucją. Działanie poza tymi granicami jest bezprawne i nieważne.\n\nArt. 3. Naród kontroluje wszystkie władze bezpośrednio przez: wolne wybory każdej z władz, referendum, obywatelską inicjatywę ustawodawczą, obywatelskie weto ustawodawcze, prawo do informacji i prawo do skargi konstytucyjnej.',
    chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5, order: 17,
  },
  {
    id: '18', paragraph: '§ 18', title: 'Władza Ustawodawcza — Sejm',
    text: 'Art. 1. Władzę ustawodawczą sprawuje jednoizbowy Sejm złożony z 314 posłów — po jednym z każdego powiatu. Zasada ta zapewnia równą reprezentację terytorialną i zbliża władzę do obywatela.\n\nArt. 2. Posłowie są wybierani w powszechnych, równych, bezpośrednich wyborach, w głosowaniu tajnym, na pięcioletnią kadencję.\n\nArt. 3. Mandat posła jest wolny — poseł wykonuje go zgodnie z sumieniem i interesem Narodu. Dyscyplina partyjna nie może nakazywać głosowania wbrew Konstytucji.\n\nArt. 4. Sejm uchwala ustawy, zatwierdza budżet państwa i ratyfikuje umowy międzynarodowe. Sejm nie sprawuje kontroli nad władzą wykonawczą — każda z władz posiada odrębny mandat Narodu i odpowiada wyłącznie przed Narodem.\n\nArt. 5. Posiedzenia Sejmu są jawne. Utajnienie obrad jest dopuszczalne wyłącznie uchwałą Sejmu podjętą większością 2/3 głosów, gdy wymaga tego bezpieczeństwo państwa.\n\nArt. 6. Osoba pełniąca funkcję publiczną, która dopuściła się przestępstwa umyślnego, podlega karze w wymiarze dwukrotnie wyższym niż przewidziany w Kodeksie Karnym, jeżeli czyn ten wywołał skutki długotrwałe lub dotknął znaczną liczbę osób. Progi określa ustawa.\n\nArt. 7. Poseł korzysta z immunitetu w zakresie sprawowania mandatu — nie ponosi odpowiedzialności za głosowania, wypowiedzi i opinie wyrażane w ramach wykonywania mandatu. Immunitet nie chroni przed odpowiedzialnością za: nawoływanie do przemocy, nawoływanie do obalenia ustroju konstytucyjnego, przestępstwa pospolite niezwiązane z wykonywaniem mandatu oraz korupcję. Uchylenie immunitetu wymaga uchwały Sejmu podjętej bezwzględną większością głosów w głosowaniu jawnym i imiennym.\n\nArt. 8. Inicjatywy ustawodawcze obywateli mają pierwszeństwo w porządku obrad Sejmu przed projektami poselskimi i rządowymi. Projekt ustawy może wnieść wyłącznie jego rzeczywisty autor: obywatele w liczbie co najmniej 0,5% uprawnionych do głosowania, poseł lub grupa posłów osobiście, lub Prezydent. Zakazane jest wnoszenie projektów ustaw przygotowanych przez podmioty zewnętrzne — korporacje, organizacje lobbingowe, podmioty zagraniczne. Poseł lub Prezydent składający projekt potwierdza pod odpowiedzialnością karną, że jest jego rzeczywistym autorem.\n\nArt. 9. Obywatele w liczbie co najmniej 0,5% uprawnionych do głosowania mogą wnieść projekt ustawy z pierwszeństwem rozpatrzenia. Sejm ma obowiązek rozpatrzyć go w ciągu 6 miesięcy.\n\nArt. 10. Obywatelskie weto ustawodawcze — w ciągu 60 dni od ogłoszenia ustawy, co najmniej 1% uprawnionych do głosowania może złożyć wniosek o referendum uchylające tę ustawę. Złożenie wniosku zawiesza wejście ustawy w życie do czasu referendum.',
    chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5, order: 18,
  },
  {
    id: '19', paragraph: '§ 19', title: 'Władza Wykonawcza — Prezydent Rzeczypospolitej',
    text: 'Art. 1. Władzę wykonawczą sprawuje Prezydent Rzeczypospolitej. Prezydent jest jednocześnie głową państwa i szefem rządu. Nie ma odrębnego stanowiska Prezesa Rady Ministrów.\n\nArt. 2. Prezydent jest wybierany w powszechnych, bezpośrednich wyborach, w głosowaniu tajnym, na pięcioletnią kadencję. Nie może sprawować urzędu przez więcej niż dwie kadencje.\n\nArt. 3. Prezydent samodzielnie powołuje i odwołuje ministrów, którzy są przed nim odpowiedzialni. Ministrowie kierują powierzonymi im działami administracji rządowej i wykonują politykę Prezydenta w granicach ustaw.\n\nArt. 4. Prezydent: wykonuje ustawy i kieruje ich wykonaniem, prowadzi politykę zagraniczną i jest zwierzchnikiem Sił Zbrojnych sprawując tę funkcję przez cywilną kontrolę wojska, ratyfikuje umowy międzynarodowe wymagające uprzedniej zgody Sejmu, wydaje rozporządzenia wykonawcze wyłącznie na podstawie wyraźnego upoważnienia ustawowego.\n\nArt. 5. Prawo weta ustawodawczego — Prezydent może w ciągu 21 dni od przekazania ustawy odmówić jej podpisania i skierować ją do ponownego rozpatrzenia przez Sejm. Sejm może odrzucić weto większością 3/5 ustawowej liczby posłów. Odrzucenie weta przez Sejm zobowiązuje Prezydenta do podpisania ustawy w ciągu 7 dni.\n\nArt. 6. Prezydent nie może samodzielnie rozwiązać Sejmu. Może złożyć wniosek o zarządzenie referendum w sprawie rozwiązania Sejmu. Decyzję podejmuje Naród.\n\nArt. 7. Ministrowie są zobowiązani do osobistego stawiennictwa na posiedzeniach Sejmu i odpowiadania na pytania posłów w ciągu 21 dni od złożenia interpelacji.\n\nArt. 8. Prezydent ponosi odpowiedzialność konstytucyjną przed Trybunałem Stanu za naruszenie Konstytucji lub ustaw. Wniosek o postawienie Prezydenta przed Trybunałem wymaga uchwały Sejmu podjętej większością 2/3 głosów przy obecności co najmniej 3/4 ustawowej liczby posłów.\n\nArt. 9. Prezydent może zostać odwołany przez Naród w referendum odwoławczym. Referendum zarządza się na wniosek co najmniej 1% uprawnionych do głosowania lub na wniosek Sejmu podjęty bezwzględną większością głosów. Sejm może jedynie wnioskować o referendum — nie może samodzielnie odwołać Prezydenta. Decyzja należy wyłącznie do Narodu.',
    chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5, order: 19,
  },
  {
    id: '20', paragraph: '§ 20', title: 'Władza Sądownicza — Niezawisłe Sądy z Mandatem Narodu',
    text: 'Art. 1. Wymiar sprawiedliwości sprawują niezawisłe sądy. Władza sądownicza jest odrębna od władzy ustawodawczej i wykonawczej i nie podlega ich kierownictwu ani ingerencji w żadnej formie.\n\nArt. 2. Sędziowie posiadają mandat społeczny udzielony bezpośrednio przez Naród. Są wyłaniani w trójstopniowym procesie: kandydaci przechodzą weryfikację merytoryczną przez niezależną komisję środowiskową złożoną z prawników i obywateli wylosowanych na wzór ławy przysięgłych; zweryfikowani kandydaci są przedstawiani opinii publicznej w jawnych i transmitowanych przesłuchaniach; ostateczny wybór należy do obywateli w bezpośrednich wyborach powszechnych.\n\nArt. 3. Sędzia sprawuje urząd przez jedną, nieodnawialną kadencję 10 lat. Nieodnawialność kadencji gwarantuje niezawisłość — sędzia nie zabiega o reelekcję i nie jest nikomu zobowiązany politycznie.\n\nArt. 4. Sędzia może być złożony z urzędu wyłącznie prawomocnym orzeczeniem Sądu Dyscyplinarnego złożonego z sędziów, za naruszenie prawa lub obowiązków sędziowskich.\n\nArt. 5. Każdy ma prawo do sądu. Prawo to nie może być wyłączone ani ograniczone żadną ustawą ani decyzją organu władzy.\n\nArt. 6. Sąd Konstytucyjny orzeka o zgodności ustaw z Konstytucją, rozstrzyga spory kompetencyjne między organami władzy i rozpatruje skargi konstytucyjne obywateli. Skarga jest rozpatrywana w ciągu 6 miesięcy od jej złożenia.\n\nArt. 7. Sąd Konstytucyjny składa się z 15 sędziów wyłanianych przez bezpośrednie wybory Narodu — na jedną, nieodnawialną 12-letnią kadencję. Wybory odbywają się w odstępach co 4 lata.\n\nArt. 8. Orzeczenia Sądu Konstytucyjnego są ostateczne i powszechnie obowiązujące. Odmowa wykonania orzeczenia Sądu Konstytucyjnego przez jakikolwiek organ władzy jest przestępstwem ściganym z urzędu.',
    chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5, order: 20,
  },
  {
    id: '21', paragraph: '§ 21', title: 'Referendum',
    text: 'Art. 1. Referendum ogólnopolskie zarządza się obowiązkowo na wniosek co najmniej 2,5% uprawnionych do głosowania. Wniosek obywatelski zobowiązuje do przeprowadzenia referendum w ciągu 90 dni. Sejm może zarządzić referendum uchwałą bezwzględną większością głosów.\n\nArt. 2. Referendum zwykłe jest wiążące przy frekwencji co najmniej 25% uprawnionych. Referendum ustrojowe — dotyczące zmian Konstytucji, przystąpienia do sojuszu wojskowego lub przeniesienia suwerenności — jest wiążące przy frekwencji co najmniej 40%. Wynik w obu przypadkach rozstrzyga bezwzględna większość głosujących.\n\nArt. 3. Obligatoryjnemu referendum ustrojowemu podlegają: zmiany Konstytucji w kwestiach określonych w § 30, przystąpienie do unii politycznej lub sojuszu wojskowego oraz przeniesienie jakiegokolwiek elementu suwerenności na organizację ponadnarodową.\n\nArt. 4. Przedmiotem referendum nie mogą być: prawa i wolności z Rozdziału II oraz indywidualna odpowiedzialność karna.',
    chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5, order: 21,
  },
  {
    id: '22', paragraph: '§ 22', title: 'Obywatelska Inicjatywa i Weto Ustawodawcze',
    text: 'Art. 1. Co najmniej 0,5% uprawnionych do głosowania może wnieść do Sejmu projekt ustawy z pierwszeństwem rozpatrzenia. Sejm jest zobowiązany rozpatrzyć go w ciągu 6 miesięcy. Odrzucenie projektu obywatelskiego może być zaskarżone do referendum na wniosek co najmniej 1% uprawnionych.\n\nArt. 2. Co najmniej 1% uprawnionych do głosowania może złożyć wniosek o referendum uchylające ustawę w ciągu 60 dni od jej ogłoszenia. Weto obywatelskie zawiesza wejście w życie ustawy do czasu przeprowadzenia referendum.\n\nArt. 3. Co najmniej 5% uprawnionych do głosowania może zainicjować zmianę Konstytucji w trybie § 29.',
    chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5, order: 22,
  },
  {
    id: '23', paragraph: '§ 23', title: 'Prawo do Informacji Publicznej',
    text: 'Art. 1. Każdy obywatel ma prawo dostępu do informacji o działalności organów władzy publicznej, wydatkowaniu środków publicznych, zawieranych umowach i podejmowanych decyzjach. Informacja jest udostępniana w ciągu 14 dni od złożenia wniosku.\n\nArt. 2. Odmowa udostępnienia informacji jest dopuszczalna wyłącznie gdy dotyczy tajemnicy państwowej zatwierdzonej przez niezależny sąd, danych osobowych osób trzecich lub trwającego postępowania karnego. Każda odmowa podlega zaskarżeniu do sądu administracyjnego w ciągu 30 dni.\n\nArt. 3. Organy władzy publicznej są zobowiązane do proaktywnego i bieżącego publikowania: budżetów i sprawozdań finansowych, treści wszelkich umów zawieranych ze środków publicznych, protokołów posiedzeń ciał kolegialnych oraz oświadczeń majątkowych wszystkich osób pełniących funkcje publiczne. Oświadczenia majątkowe są jawne i dostępne publicznie.',
    chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5, order: 23,
  },
  {
    id: '24', paragraph: '§ 24', title: 'Zakaz Konfliktu Interesów i Rejestr Lobbingu',
    text: 'Art. 1. Osoba pełniąca funkcję publiczną — poseł, minister, Prezydent, sędzia, wyższy urzędnik — nie może w czasie sprawowania tej funkcji: prowadzić działalności gospodarczej korzystającej z zasobów publicznych, zasiadać w zarządach lub radach nadzorczych spółek prawa handlowego, świadczyć odpłatnych usług doradczych podmiotom prywatnym, pobierać wynagrodzenia od jakichkolwiek podmiotów innych niż Skarb Państwa.\n\nArt. 2. Ministrowie nie mogą być jednocześnie posłami. Posłowie nie mogą pełnić funkcji w rządzie.\n\nArt. 3. Zakaz nepotyzmu — osoby pełniące kierownicze funkcje publiczne nie mogą zatrudniać w podległych sobie instytucjach małżonków, krewnych i powinowatych do drugiego stopnia.\n\nArt. 4. Każdy kontakt osoby pełniącej funkcję publiczną z podmiotami zewnętrznymi w sprawach dotyczących stanowienia lub wykonywania prawa podlega obowiązkowemu wpisowi do jawnego rejestru publicznego. Rejestr zawiera datę, strony spotkania i ogólny temat. Brak wpisu stanowi naruszenie Konstytucji i pociąga do odpowiedzialności karnej. Szczegółowe zasady prowadzenia rejestru określa ustawa.\n\nArt. 5. Naruszenie zakazów z niniejszego paragrafu skutkuje natychmiastową utratą mandatu lub funkcji z mocy prawa i pociąga do odpowiedzialności karnej ściganej z urzędu. Przedawnienie karalności tych czynów nie biegnie w czasie sprawowania funkcji publicznej.',
    chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5, order: 24,
  },
  {
    id: '25', paragraph: '§ 25', title: 'Ochrona Sygnalistów, Dziennikarzy i Prawo do Skargi',
    text: 'Art. 1. Osoba ujawniająca w dobrej wierze informacje o naruszeniu prawa przez organy władzy publicznej korzysta z pełnej ochrony prawnej. Represjonowanie sygnalistów przez organy państwowe stanowi przestępstwo ścigane z urzędu.\n\nArt. 2. Dziennikarstwo służące informowaniu obywateli o działalności organów władzy publicznej jest działalnością szczególnie chronioną. Dziennikarz ujawniający informacje o naruszeniach prawa przez władzę korzysta z ochrony tożsamej z ochroną sygnalisty.\n\nArt. 3. Tajemnica dziennikarska — ochrona tożsamości źródeł informacji — jest nienaruszalna i nie może być uchylona żadną decyzją organu władzy wykonawczej. Jej uchylenie wymaga wyłącznie wyroku niezawisłego sądu w sprawie o najcięższe przestępstwa.\n\nArt. 4. Wolność dziennikarska oznacza prawo i obowiązek rzetelnego informowania suwerena o faktach. Nie oznacza prawa do narzucania ideologii ani kształtowania opinii publicznej w interesie podmiotów innych niż Naród.\n\nArt. 5. Każdy obywatel ma prawo składać skargi i petycje do każdego organu władzy publicznej. Organ ma obowiązek rozpatrzyć skargę i udzielić merytorycznej odpowiedzi w ciągu 30 dni.\n\nArt. 6. Rzecznik Praw Obywatelskich stoi na straży praw i wolności obywateli. Jest powoływany przez Sejm bezwzględną większością głosów na wniosek organizacji pozarządowych. Rzecznik jest niezależny od wszystkich organów władzy.\n\nArt. 7. Każdy ma prawo do wniesienia skargi konstytucyjnej do Sądu Konstytucyjnego jeśli akt prawny lub działanie organu władzy narusza jego prawa konstytucyjne.',
    chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5, order: 25,
  },
  {
    id: '26', paragraph: '§ 26', title: 'Odpowiedzialność Karna Osób Sprawujących Władzę',
    text: 'Art. 1. Wszystkie osoby pełniące funkcje publiczne — posłowie, ministrowie, Prezydent, sędziowie, wyżsi urzędnicy — podlegają surowszej odpowiedzialności karnej niż zwykli obywatele, gdy popełnione przez nich przestępstwo miało długotrwałe skutki lub dotknęło znaczną liczbę osób. Progi określa ustawa.\n\nArt. 2. Prezydent, ministrowie i sędziowie ponoszą odpowiedzialność konstytucyjną przed Trybunałem Stanu za naruszenie Konstytucji lub ustaw.\n\nArt. 3. Przedawnienie karalności przestępstw popełnionych przez osoby piastujące władzę publiczną nie biegnie w czasie sprawowania przez nich urzędu.',
    chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5, order: 26,
  },
  {
    id: '27', paragraph: '§ 27', title: 'Zasada Legalności i Precyzji Prawa',
    text: 'Art. 1. Organy władzy publicznej działają wyłącznie na podstawie i w granicach prawa. Wszelkie działania organów państwa bez wyraźnej podstawy prawnej są nieważne.\n\nArt. 2. Przepisy prawne muszą być jasne, jednoznaczne i dostępne. Prawo niejasne lub wieloznaczne jest niezgodne z Konstytucją w zakresie tej niejasności. Żaden przepis nie może pozostawiać organom władzy swobody interpretacji prowadzącej do dowolności stosowania.\n\nArt. 3. Zakaz retroaktywności — prawo nie działa wstecz. Prawa nabyte nie mogą być odbierane bez uzasadnienia ważnym interesem publicznym i bez odszkodowania.\n\nArt. 4. Organy władzy publicznej są zobowiązane do przestrzegania zasady proporcjonalności — stosowane środki muszą być adekwatne do celu i możliwie najmniej uciążliwe dla obywateli.',
    chapter: 'Rozdział V — Praworządność', stars: 5, order: 27,
  },
  {
    id: '28', paragraph: '§ 28', title: 'Dostęp do Wymiaru Sprawiedliwości',
    text: 'Art. 1. Każdy ma prawo do sądu. Pierwsze posiedzenie w sprawach cywilnych odbywa się w ciągu 60 dni od złożenia pozwu. Wyrok w pierwszej instancji zapada w ciągu 18 miesięcy. Przekroczenie tych terminów daje stronie prawo do odszkodowania od Skarbu Państwa.\n\nArt. 2. Pomoc prawna dla osób nieposiadających środków finansowych jest gwarantowana ze środków publicznych na poziomie umożliwiającym skuteczną obronę swoich praw.',
    chapter: 'Rozdział V — Praworządność', stars: 5, order: 28,
  },
  {
    id: '29', paragraph: '§ 29', title: 'Tryb Zmiany Konstytucji',
    text: 'Art. 1. Zmianę Konstytucji może zaproponować: co najmniej 1/5 ustawowej liczby posłów, Prezydent Rzeczypospolitej lub co najmniej 5% uprawnionych do głosowania.\n\nArt. 2. Projekt zmiany Konstytucji wymaga uchwalenia przez Sejm większością co najmniej 2/3 głosów przy obecności co najmniej połowy ustawowej liczby posłów.\n\nArt. 3. Po uchwaleniu przez Sejm każdy projekt zmiany Konstytucji jest obowiązkowo poddawany pod referendum ogólnopolskie. Zmiana wchodzi w życie jeśli zaaprobuje ją bezwzględna większość głosujących przy frekwencji co najmniej 40%.\n\nArt. 4. Między uchwaleniem przez Sejm a przeprowadzeniem referendum musi upłynąć co najmniej 90 dni, aby Naród mógł zapoznać się z treścią proponowanej zmiany.',
    chapter: 'Rozdział VI — Zmiana Konstytucji', stars: 5, order: 29,
  },
  {
    id: '30', paragraph: '§ 30', title: 'Klauzule Niezmienialności — Jądro Konstytucji',
    text: 'Art. 1. Następujących postanowień Konstytucji nie można zmienić w żadnym trybie:\n— suwerenność Narodu jako jedynego źródła władzy (§ 1);\n— przyrodzona godność człowieka i bezwzględny zakaz tortur (§ 3, § 8 art. 3);\n— zasada trójpodziału władzy i odrębnych mandatów społecznych każdej z władz (§ 17);\n— niezawisłość sądów i prawo każdego do sądu (§ 20);\n— wolne, bezpośrednie i powszechne wybory wszystkich władz przez Naród;\n— prawo Narodu do referendum i obywatelskiego weta ustawodawczego (§ 21, § 22);\n— prawo obywatela do posiadania broni jako gwarancja wolności Narodu (§ 9).\n\nArt. 2. Postanowienia te stanowią nienaruszalne jądro Konstytucji — ich zniesienie oznaczałoby koniec demokratycznego kontraktu społecznego. Sąd Konstytucyjny odmawia stwierdzenia zgodności z Konstytucją każdej zmiany naruszającej to jądro, nawet jeśli została przyjęta większością wymaganą przez § 29.',
    chapter: 'Rozdział VI — Zmiana Konstytucji', stars: 5, order: 30,
  },
  {
    id: '31', paragraph: '§ 31', title: 'Obowiązywanie i Pierwszeństwo Konstytucji',
    text: 'Art. 1. Konstytucja jest bezpośrednio stosowana przez wszystkie sądy i organy władzy. Sędzia który stwierdza sprzeczność ustawy z Konstytucją odmawia jej zastosowania i kieruje pytanie prawne do Sądu Konstytucyjnego.\n\nArt. 2. Wszystkie obowiązujące ustawy, rozporządzenia i akty prawne zachowują moc o ile nie są sprzeczne z Konstytucją. Niezgodności są usuwane przez Sejm w następujących terminach: przepisy bezpośrednio naruszające prawa obywatelskie — w ciągu 2 lat; całość porządku prawnego — w ciągu 5 lat. Sąd Konstytucyjny może na wniosek Sejmu przedłużyć termin pięcioletni o kolejne 2 lata w wyjątkowych i uzasadnionych przypadkach.',
    chapter: 'Rozdział VII — Postanowienia Końcowe', stars: 5, order: 31,
  },
  {
    id: '32', paragraph: '§ 32', title: 'Ratyfikacja przez Naród',
    text: 'Art. 1. Niniejsza Konstytucja wchodzi w życie po zatwierdzeniu jej przez Naród w ogólnopolskim referendum ratyfikacyjnym przy frekwencji co najmniej 40% uprawnionych i pozytywnym wyniku bezwzględnej większości głosujących.\n\nArt. 2. Referendum ratyfikacyjne jest jedynym trybem przyjęcia niniejszej Konstytucji. Żaden organ władzy nie może wprowadzić Konstytucji w życie bez uprzedniej zgody Narodu wyrażonej w referendum.',
    chapter: 'Rozdział VII — Postanowienia Końcowe', stars: 5, order: 32,
  },
  {
    id: '33', paragraph: '§ 33', title: 'Zobowiązanie',
    text: 'Niniejsza Konstytucja jest zobowiązaniem — nie obietnicą.\n\nZobowiązaniem Narodu wobec siebie samego, wobec swoich dzieci i wnuków.\n\nZobowiązaniem władzy wobec Narodu — do służenia, nie panowania.\n\nJej przestrzeganie to nie obowiązek, lecz fundament wspólnoty, którą wybieramy.\n\n— Naród Polski',
    chapter: 'Rozdział VII — Postanowienia Końcowe', stars: 5, order: 33,
  },
]
