import { neon } from '@neondatabase/serverless'
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

const sql = neon(process.env.DATABASE_URL)

const articles = [
  { id: 'p0-0', chapter: 'Preambuła', stars: 5 },
  { id: '1-1', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '1-2', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '1-3', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '1-4', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '2-1', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '2-2', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '2-3', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '2-4', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '3-1', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '3-2', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '3-3', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '4-1', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '4-2', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '4-3', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '4-4', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '5-1', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '5-2', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '5-3', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '6-1', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '6-2', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '6-3', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '6-4', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '7-1', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '7-2', chapter: 'Rozdział I — Zasady Ustrojowe: Naród jako Suweren', stars: 5 },
  { id: '8-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '8-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '8-3', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '8-4', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '9-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '9-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '9-3', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '10-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '10-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '10-3', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '10-4', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '10-5', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '10-6', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '11-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '11-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '11-3', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '11-4', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '12-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '12-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '12-3', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '13-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '13-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '13-3', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '13-4', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '13-5', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '13-6', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '13-7', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-3', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-4', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-5', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-6', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-7', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-8', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-9', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '14-10', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '15-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '15-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '16-1', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '16-2', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '16-3', chapter: 'Rozdział II — Prawa i Wolności Obywatelskie', stars: 5 },
  { id: '17-1', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '17-2', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '17-3', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-1', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-2', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-3', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-4', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-5', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-6', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-7', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-8', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-9', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '18-10', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-1', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-2', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-3', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-4', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-5', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-6', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-7', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-8', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '19-9', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '20-1', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '20-2', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '20-3', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '20-4', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '20-5', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '20-6', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '20-7', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '20-8', chapter: 'Rozdział III — Ustrój Państwa: Trójpodział Władzy pod Kontrolą Narodu', stars: 5 },
  { id: '21-1', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '21-2', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '21-3', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '21-4', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '22-1', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '22-2', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '22-3', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '23-1', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '23-2', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '23-3', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '24-1', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '24-2', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '24-3', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '24-4', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '24-5', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '25-1', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '25-2', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '25-3', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '25-4', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '25-5', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '25-6', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '25-7', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '26-1', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '26-2', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '26-3', chapter: 'Rozdział IV — Kontrola Władzy przez Naród', stars: 5 },
  { id: '27-1', chapter: 'Rozdział V — Praworządność', stars: 5 },
  { id: '27-2', chapter: 'Rozdział V — Praworządność', stars: 5 },
  { id: '27-3', chapter: 'Rozdział V — Praworządność', stars: 5 },
  { id: '27-4', chapter: 'Rozdział V — Praworządność', stars: 5 },
  { id: '27-5', chapter: 'Rozdział V — Praworządność', stars: 5 },
  { id: '28-1', chapter: 'Rozdział V — Praworządność', stars: 5 },
  { id: '28-2', chapter: 'Rozdział V — Praworządność', stars: 5 },
  { id: '29-1', chapter: 'Rozdział VI — Zmiana Konstytucji', stars: 5 },
  { id: '29-2', chapter: 'Rozdział VI — Zmiana Konstytucji', stars: 5 },
  { id: '29-3', chapter: 'Rozdział VI — Zmiana Konstytucji', stars: 5 },
  { id: '29-4', chapter: 'Rozdział VI — Zmiana Konstytucji', stars: 5 },
  { id: '30-1', chapter: 'Rozdział VI — Zmiana Konstytucji', stars: 5 },
  { id: '30-2', chapter: 'Rozdział VI — Zmiana Konstytucji', stars: 5 },
  { id: '31-1', chapter: 'Rozdział VII — Postanowienia Końcowe', stars: 5 },
  { id: '31-2', chapter: 'Rozdział VII — Postanowienia Końcowe', stars: 5 },
  { id: '32-1', chapter: 'Rozdział VII — Postanowienia Końcowe', stars: 5 },
  { id: '32-2', chapter: 'Rozdział VII — Postanowienia Końcowe', stars: 5 },
  { id: '33-1', chapter: 'Rozdział VII — Postanowienia Końcowe', stars: 5 }
]

// Ten skrypt jest wyłącznie addytywny — nigdy nie kasuje istniejących
// artykułów, głosów ani wyników. ON CONFLICT DO NOTHING pomija artykuły,
// które już są w bazie, więc bezpiecznie dogrywa tylko nowo dodane
// (np. w lib/articles.ts) bez ryzyka utraty dotychczasowych głosów.
let added = 0
for (const art of articles) {
  const inserted = await sql`
    INSERT INTO articles (id, paragraph, title, text, chapter, stars, "order")
    VALUES (${art.id}, ${art.id}, ${art.id}, ${art.id}, ${art.chapter}, ${art.stars}, 0)
    ON CONFLICT (id) DO NOTHING
    RETURNING id
  `
  if (inserted.length > 0) added++
  await sql`
    INSERT INTO vote_results (article_id, yes_count, no_count)
    VALUES (${art.id}, 0, 0)
    ON CONFLICT (article_id) DO NOTHING
  `
}

console.log(`Seed zakończony — sprawdzono ${articles.length} artykułów, dodano ${added} nowych. Istniejące dane pozostały nietknięte.`)
